= Open Source Development

== Readings

TIP: Carefully read the first sentence of every paragraph before deciding
whether to skip or read the rest of the paragraph, since writers often
state the point upfront and then support it in subsequent sentences.
In short, you can read quickly with high comprehension by skipping the
supporting material, if you understand the point and how writers write.
Of course, if you don't understand the point, then read everything carefully.
Obviously, this strategy doesn't always work: not all documents
fit the topic sentence followed by supporting points structure of essays.
For example, narratives often instead have dialogue among characters,
but those are even easier to read quickly than large walls of text.
Also, some writers put in pointless filler that doesn't go anywhere,
or even worse, bury the point in the middle of the paragraph.
But, writers who understand their audience realize that to get people to
read their work, they must make their work easy to skim.
Now, did you see what I just did there?
If you were thinking, this paragraph is itself a giant wall of text,
and I could have ignored the rest, and then realized that this is all a
bit meta, then you not only understand the definition of the
word meta, but you also ignored my advice about how to speed
read, proving that you are kind of person who does the reading completely.
Obviously, reading the whole paragraph gives you some nuance that can be
rewarding, but then again, I think we can agree that the first sentence
captured the rest of this paragraph pretty well.

=== Definitions and licenses

What is free software?
What is open source software?
What's the difference?
What's copyleft? What's permissive?
What's the difference among the licenses?

* https://www.gnu.org/philosophy/free-sw.html[Free software definition]
* http://opensource.org/osd-annotated[Open source definition]
* https://www.gnu.org/philosophy/license-list.html[Licenses galore]

=== Historical background

When did open source software start?
What were the major accomplishments?
Who were the key players?
What has changed over the decades?
Why do folks write open source software?

* https://www.youtube.com/watch?v=k84FMc1GF8M[Revolution OS]
* http://www.catb.org/esr/writings/cathedral-bazaar/cathedral-bazaar/[The Cathedral And the Bazaar]
* http://www.oreilly.com/openbook/opensources/book/index.html[Open Sources: Voices from the Open Source Revolution]

=== Freedom, Politics, Ethics

Who is in control of your computer?
What do we give up when we cede control to others?
What do we gain?
Is it okay for others to decide what you can do with your computer?
If so, when?

* http://dash.harvard.edu/bitstream/handle/1/4455262/Zittrain_Future%20of%20the%20Internet.pdf?sequence=1[The Future of the Internet - And How to Stop It]
* http://shop.fsf.org/product/free-software-free-society-2/[Free Software, Free Society]
* http://gabriellacoleman.org/Coleman-Coding-Freedom.pdf[Coding Freedom]

=== Money

Who produces open source software?
Who pays for it?
Who profits from it?
How can open source developers earn a living?

* http://www.catb.org/esr/writings/magic-cauldron/magic-cauldron.html[The Magic Cauldron]
* http://dreamsongs.com/IHE/IHE.html[Innovation Happens Elsewhere]

=== Git

Git. Huh. What is it good for?

* https://www.youtube.com/watch?v=1ffBJ4sVUb4[Git for ages 4 and up]
* http://rypress.com/tutorials/git/index[Ry's Git Tutorial]
* http://www-cs-students.stanford.edu/~blynn/gitmagic/[Git Magic]

=== Studying code

What can we learn from reading source code?
What can source code teach us about software development?

* http://www.aosabook.org/en/index.html[The Architecture of Open Source Applications]
* http://neverworkintheory.org/[It Will Never Work in Theory]

=== Writing open source software

How does one go about running and/or contributing to an open source project?

* http://producingoss.com/en/index.html[Producing Open Source Software]
* http://open-advice.org/[Open Advice: FOSS: What We Wish We Had Known When We Started]
* http://www.catb.org/esr/faqs/smart-questions.html[How to ask questions the smart way]
* http://artofcommunityonline.org/Art_of_Community_Second_Edition.pdf[The Art of Community: Second Edition]

=== Beyond software

Do the principles of free and open source software apply beyond software?
If so, how?

* http://www.gnu.org/philosophy/fsfs/rms-essays.pdf[Free software, Free society]
* http://www.free-culture.cc/freeculture.pdf[Free culture]

=== Further reading

Need more books to read?

* https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#open-source-ecosystem[Gigantic list of free programming books]
* https://opensource.com/resources/ebooks[Open source reading list]

== Agenda

* Git and hosting setup
* Reading groups, breakouts and discussion
* Study (and contribute to) an open source project
** https://openhatch.org/[Open Hatch]
** https://github.com/explore[Trending repositories]
** https://www.google-melange.com/gsoc/org/list/public/google/gsoc2015[GSOC 2015]
